baseURL = "https://ubiquitousaugmented.fashion/"
languageCode = "en-us"
title = "Ubiquitous Augmented Fashion"
theme = ["hugo-video", "ubiquitous-augmented-fashion-theme"]

[Params.documentSettings]
    logoURL = "/images/uaf-logo.png"
    copyrightName = "Ubiquitous Augmented Fashion"

[markup.goldmark.renderer]
unsafe = true